Update to new implementation syntax
xodio/xod-docs pull request #192
Opened 2020-09-02 14:11 UTC by evgenykochetkov

2020-09-02 16:35 UTC, gabbapeople commented
Everything seems clear 👍

2020-09-03 12:07 UTC, nkrkv requested changes
Excellent rework!

Found a couple of overlooks though.

2020-09-03 12:07 UTC, nkrkv commented on docs/guide/wrapping-arduino-libraries/README.md
> +    uint8_t mem[sizeof(Adafruit_PN532)];
Ahaaa… Here’s a win of the new system. This could be easily simplified to:

```suggestion
    // Keep Adafruit_PN532 object in state.
    // Instead of the `reset` port, specify `NOT_A_PORT`, since it is not needed
    Adafruit_PN532(constant_input_IRQ, NOT_A_PORT);
```

2020-09-03 12:07 UTC, nkrkv commented on docs/guide/wrapping-arduino-libraries/README.md
> +        raiseError(ctx); // Initialization error
Extra indent level is necessary

2020-09-03 12:07 UTC, nkrkv commented on docs/guide/wrapping-arduino-libraries/README.md
> +        &uidLength
Indent

2020-09-04 12:32 UTC, brusherru reviewed
What about adding small notes in changed articles with a link to "migration guide" or something like this? In case, that someone dives deep in the C++ code of a third-party library, this user might be confused that this code does not look like a code from guides :)

2020-09-04 12:32 UTC, brusherru commented on docs/guide/custom-types/README.md
> +    CStringView view = CStringView(buff);
Probably, it would be nice to add why exactly this syntax, not just `CStringView view(buff);` 🤔

2020-09-04 13:24 UTC, nkrkv approved these changes
:+1:

2020-09-04 13:24 UTC, nkrkv commented on docs/guide/custom-types/README.md
> +    CStringView view = CStringView(buff);
Because it’s the way C++ works. We don’t teach C++, we explain XOD-specific API

2020-09-04 14:31 UTC, merged