Feat records
xodio/xod-docs pull request #209
Opened 2020-10-20 08:54 UTC by brusherru

Guide for the new records feature ( https://github.com/xodio/xod/pull/2051 ).

2020-10-20 10:01 UTC, nkrkv requested changes

2020-10-20 10:01 UTC, nkrkv commented on docs/guide/records/README.md
> +To simplify the packing and unpacking process without coding a C++ implementation manually, the XOD has a particular marker node `xod/patch-nodes/record`. When the user places this node on the patch
A reader highly likely knows nothing about C++. Suggest getting rid of any C++ mention in the body: the knowledge is not required to actually _solve the problems_ the records intend to solve.

C++ details are important, though. Just concentrate them in a dedicated section closer to the end of the article.

2020-10-20 10:01 UTC, nkrkv commented on docs/guide/records/README.md
> +            typeof_Z Z;
Do not forget prefixes

2020-10-20 10:01 UTC, nkrkv commented on docs/guide/records/README.md
> +        record._2 = getValue<input_Z>(ctx);
Wrong field names

2020-10-21 12:04 UTC, brusherru commented
Also, I've just added a paragraph in C++ section about unlabeled terminals within the last fixup commit.

2020-10-21 12:28 UTC, nkrkv requested changes

2020-10-21 12:28 UTC, nkrkv commented on docs/guide/records/README.md
> +To simplify the packing and unpacking process without coding a C++ implementation manually, the XOD has a particular marker node `xod/patch-nodes/record`. When the user places this node on the patch
```suggestion
To simplify the packing and unpacking process without coding a C++ implementation manually, XOD has a marker node `xod/patch-nodes/record`. When you place this node on the patch with some input terminals and `output-self` node, XOD automatically generates the code necessary to pack the multiple inputs into a single record. It also creates an unpack patch which can access the record field values.
```

2020-10-21 12:28 UTC, nkrkv commented on docs/guide/records/README.md
> +Grouping of values is useful when you need to pass a bunch of data in the several nodes without insane linking net all over your patches. This guide will not consider examples of such complex program
```suggestion
Grouping of values is useful when you need to pass a bunch of data in the several nodes without insane linking net all over your patches. This guide does not consider examples of such complex programs but gives some use cases of how to pack these data and use it where necessary.
```

2020-10-21 12:28 UTC, nkrkv commented on docs/guide/records/README.md
> +Let's imagine that we want to pack outputs from an accelerometer. It has three data values of type Number, which represents acceleration on X, Y, and Z axes. Let's create a record for them.
```suggestion
Imagine we want to pack outputs from an accelerometer. It has three data values of type `Number`, which represent acceleration along X, Y, and Z axes. Let's create a record for them. To do this, we are going to create a new record type:
```

2020-10-21 12:28 UTC, nkrkv commented on docs/guide/records/README.md
> +Also, the `record` marker automatically creates a `@/unpack-3d-acceleration` patch, which you can use to get values from the record without diving in the C++.
```suggestion
Note, the `record` marker automatically created a `@/unpack-3d-acceleration` patch, which you can use to get the plain values back out from the record.
```

2020-10-21 12:28 UTC, nkrkv commented on docs/guide/records/README.md
> +You can also find out created `@/input-3d-acceleration` and `@/output-3d-acceleration` terminal patches in the project browser. So you can encapsulate some logic over your record inside a new patch.
And please, cross-link “custom type” to the existing guide article. BTW, are there any organic places to add _inbound_ links from other guide articles?

```suggestion
As for any other custom type, you can also find out created `@/input-3d-acceleration` and `@/output-3d-acceleration` terminal patches in the project browser. So you can encapsulate some logic over your record inside a new patch. To do so, you need to create a new patch and place the `@/input-3d-acceleration` terminal and the `@/unpack-3d-acceleration` node and work with it as usual if you want to change some values in the record, place a new `@/3d-acceleration` node and link it with `@/output-3d-acceleration`.
```

2020-10-21 12:28 UTC, nkrkv commented on docs/guide/records/README.md
> +Records can be serialized to JSON format. JSON is a widespread data interchange format. Most cloud services can work with this format. In this way, records make it easy to send data to various servic
```suggestion
Records can be serialized to JSON. JSON is a widespread data interchange format. Most cloud services can work with it. In this way, records make it easy to send data to various services, including [XOD Cloud Feeds](../getting-started-with-feeds/) and especially [multiple time series](../multiple-time-series/).
```

Cross-link guides with relative paths to make the linking work when previewing on GitHub

2020-10-21 12:28 UTC, nkrkv commented on docs/guide/records/README.md
> +However, most of the custom types have no `to-json` specializations, so you'll get a compilation error if you try to serialize a record, which contains, for example, an `i2c` type. But, if you really
```suggestion
However, most of the custom types have no `to-json` specializations, so you'll get a compilation error if you try to serialize a record, which contains, for example, an `i2c` type. But, if you really need to serialize some custom type you can create `to-json` [specialization](../generics/#specializations) manually. It should output a JSON-serialized string.
```

2020-10-21 12:28 UTC, nkrkv commented on docs/guide/records/README.md
> +Some nodes representing hardware devices and define a custom type can be defined using the same record mechanism instead of implementing it in C++.
```suggestion
Some nodes representing hardware devices using a custom type may be defined using the same record mechanism instead of implementing them in C++.
```

2020-10-21 12:28 UTC, nkrkv commented on docs/guide/records/README.md
> +- no need to define custom methods in the type.
> no need to define custom methods in the type

This is unclear to me. Even after several re-reads :) Looks like it is still highly-bound to C++ stuff.

2020-10-21 12:28 UTC, nkrkv commented on docs/guide/records/README.md
> +For example, the standard library [`xod-dev/ds-rtc`](https://xod.io/libs/xod-dev/ds-rtc) requires an I2C bus and address of the device. These values pack in the records without any problems. We have
> We have already replaced a C++ implementation of the custom type with a record marker

This one sounds stale. Should be timeless. E.g:

> This library uses a record to pass the bus object along with address as a single type, check out how it works.

2020-10-21 12:28 UTC, nkrkv commented on docs/guide/records/README.md
> +## How records represented in C++
```suggestion
## C++ representation
```

2020-10-21 12:28 UTC, nkrkv commented on docs/guide/records/README.md
> +Records is a `struct` with fields of input terminals. Each field has the same type as terminal and uses label in naming the field. For example, if you set the label of terminal to `X` it will be `fie
```suggestion
A record is laid out as a `struct` with fields of input terminals. Each field has the same type as the terminal and uses its label as the name, prefixed with `field_`. For example, if you set the label of a terminal to `X` it will be `field_X` in the `struct`.
```

2020-10-21 12:28 UTC, nkrkv commented on docs/guide/records/README.md
> +Records passed to the outputs as is, not a pointer. So records are an immutable data type. If you want to change some record values, you have to create a new instance of the record with new values.
```suggestion
Records are passed to the outputs by value, not by reference. So a record is an immutable data type. If you want to change some record values, you have to create a new instance of the record with new values.
```

2020-10-21 12:28 UTC, nkrkv commented on docs/guide/records/README.md
> +If you want to create your own C++ implementation for some purposes with records on inputs, you can get the record and access it fields the same way as in the implementation of the unpack record patc
```suggestion
If you want to create your own C++ implementation for some purposes with records on inputs, you can get the record and access its fields the same way as in the implementation of the unpack record patch above.
```

2020-10-21 13:46 UTC, brusherru commented on docs/guide/records/README.md
> +Let's imagine that we want to pack outputs from an accelerometer. It has three data values of type Number, which represents acceleration on X, Y, and Z axes. Let's create a record for them.
Without `Let's create a record for them.` I guess?

2020-10-21 13:57 UTC, brusherru commented on docs/guide/records/README.md
> +- no need to define custom methods in the type.
Okay. I think I can get rid of this part at all.
Including C++ libraries might be done further in the action nodes, I think :)

2020-10-21 14:54 UTC, nkrkv approved these changes
:+1:

2020-10-26 10:30 UTC, nkrkv approved these changes

2020-10-27 16:38 UTC, evgenykochetkov commented on docs/guide/records/README.md
> +        Type record = getValue<output_OUT>(ctx);
IIRC, it was optimised to just `Type record ;`

2020-10-27 16:39 UTC, evgenykochetkov approved these changes
LGTM

2020-10-28 10:53 UTC, merged